import PDFDocument from 'pdfkit';
import { COMPANY_NAME, CURRENCY } from './constants.js';

const money = (n) => `${CURRENCY} ${(Number(n) || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

/**
 * Stream a quotation PDF to `res`.
 * @param {object} res Express response
 * @param {object} q quotation row with items JSON parsed
 */
export function sendQuotationPdf(res, q) {
  const items = typeof q.items === 'string' ? JSON.parse(q.items) : q.items || [];
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="${q.quotation_number}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fillColor('#312e81').fontSize(22).font('Helvetica-Bold').text(COMPANY_NAME, { continued: false });
  doc.fontSize(9).font('Helvetica').fillColor('#6b7280').text('Professional event planning & management');
  doc.moveDown(0.4);
  doc.fontSize(16).fillColor('#111827').text('Quotation', { continued: false });
  doc.fontSize(10).fillColor('#374151').text(`Quotation #: ${q.quotation_number}`);
  doc.text(`Date: ${String(q.created_at || '').slice(0, 10)}`);
  doc.moveDown(0.6);

  // Client box
  doc.roundedRect(48, doc.y, 300, 74, 6).stroke('#e5e7eb');
  doc.fillColor('#312e81').fontSize(10).font('Helvetica-Bold').text('BILL TO', 60, doc.y + 10);
  doc.fillColor('#111827').fontSize(11).text(q.client_name, 60, doc.y + 4);
  doc.font('Helvetica').fontSize(9).fillColor('#4b5563');
  if (q.client_phone) doc.text(`Phone: ${q.client_phone}`, 60, doc.y + 2);
  if (q.client_email) doc.text(`Email: ${q.client_email}`, 60, doc.y + 2);
  doc.y += 16;

  // Event details
  doc.fillColor('#312e81').fontSize(10).font('Helvetica-Bold').text('EVENT DETAILS');
  doc.font('Helvetica').fontSize(9).fillColor('#4b5563');
  if (q.event_name) doc.text(`Event: ${q.event_name}`);
  if (q.event_date) doc.text(`Date: ${q.event_date}`);
  if (q.venue) doc.text(`Venue: ${q.venue}`);
  doc.moveDown(0.8);

  // Items table
  const startY = doc.y;
  doc.fontSize(9).fillColor('#ffffff');
  doc.rect(48, startY, 510, 20).fill('#312e81');
  doc.fillColor('#ffffff').font('Helvetica-Bold');
  doc.text('#', 54, startY + 6);
  doc.text('Description', 72, startY + 6, { width: 260 });
  doc.text('Qty', 340, startY + 6, { width: 40, align: 'right' });
  doc.text('Unit Price', 388, startY + 6, { width: 80, align: 'right' });
  doc.text('Amount', 476, startY + 6, { width: 80, align: 'right' });
  doc.moveDown(1.1);

  doc.font('Helvetica').fillColor('#111827');
  items.forEach((item, i) => {
    const amount = (Number(item.qty) || 0) * (Number(item.unit_price) || 0);
    doc.fontSize(9);
    doc.text(String(i + 1), 54, doc.y);
    doc.text(item.description || '-', 72, doc.y, { width: 260 });
    doc.text(String(item.qty ?? 1), 340, doc.y, { width: 40, align: 'right' });
    doc.text(money(item.unit_price), 388, doc.y, { width: 80, align: 'right' });
    doc.text(money(amount), 476, doc.y, { width: 80, align: 'right' });
    doc.moveDown(0.4);
  });

  // Totals
  doc.moveDown(0.6);
  const drawTotal = (label, value) => {
    doc.fontSize(9).fillColor('#4b5563').font('Helvetica').text(label, 350, doc.y);
    doc.fillColor('#111827').font('Helvetica-Bold').text(value, 430, doc.y - 10, { width: 128, align: 'right' });
    doc.moveDown(0.4);
  };
  drawTotal('Subtotal', money(q.subtotal));
  if (Number(q.discount) > 0) drawTotal('Discount', `- ${money(q.discount)}`);
  if (Number(q.tax) > 0) drawTotal('Tax', money(q.tax));
  doc.moveDown(0.2);
  doc.rect(430, doc.y, 128, 24).fill('#312e81');
  doc.fillColor('#ffffff').fontSize(11).text('TOTAL', 438, doc.y + 7);
  doc.text(money(q.total), 452, doc.y + 7, { width: 100, align: 'right' });
  doc.moveDown(1.4);

  if (q.notes) {
    doc.fontSize(9).fillColor('#374151').font('Helvetica-Bold').text('Notes');
    doc.font('Helvetica').fillColor('#4b5563').text(q.notes, { width: 460 });
    doc.moveDown(1);
  }

  doc.moveDown(1.2);
  doc.fontSize(9).fillColor('#9ca3af').font('Helvetica').text(
    `Generated by ${COMPANY_NAME} • Thank you for your business!`,
    { align: 'center' }
  );

  doc.end();
}

/**
 * Stream a financial report PDF to `res`.
 * @param {object} res Express response
 * @param {object} report { range, from, to, summary, rows } as built by routes/reports.js
 */
export function sendReportPdf(res, report) {
  const { from, to, summary, rows } = report;
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  const safe = (s) => String(s || '').replace(/[^\w-]+/g, '-').replace(/^-+|-+$/g, '') || 'report';
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="report-${safe(from)}-to-${safe(to)}.pdf"`);
  doc.pipe(res);

  const labelFor = (range) =>
    range === 'daily' ? 'Daily' : range === 'yearly' ? 'Yearly' : range === 'custom' ? 'Custom range' : 'Monthly';

  // Header
  doc.fillColor('#312e81').fontSize(22).font('Helvetica-Bold').text(COMPANY_NAME, { continued: false });
  doc.fontSize(9).font('Helvetica').fillColor('#6b7280').text('Professional event planning & management');
  doc.moveDown(0.4);
  doc.fontSize(16).fillColor('#111827').text(`${labelFor(report.range)} Financial Report`, { continued: false });
  doc.fontSize(10).fillColor('#374151').text(`Period: ${from}  →  ${to}`);
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`);
  doc.moveDown(0.8);

  // Summary boxes (2 x 2)
  const boxes = [
    { label: 'Income', value: money(summary.income), color: '#16a34a' },
    { label: 'Expense', value: money(summary.expense), color: '#dc2626' },
    { label: 'Profit', value: money(summary.profit), color: '#312e81' },
    { label: 'Paid to staff', value: money(summary.payments), color: '#d97706' },
  ];
  const boxW = 249, boxH = 62, gap = 12;
  boxes.forEach((b, i) => {
    const col = i % 2, row = Math.floor(i / 2);
    const x = 48 + col * (boxW + gap);
    const y = doc.y + row * (boxH + gap);
    doc.roundedRect(x, y, boxW, boxH, 6).fillAndStroke('#f4f5fb', '#e5e7eb');
    doc.fillColor(b.color).fontSize(16).font('Helvetica-Bold').text(b.value, x + 14, y + 12, { width: boxW - 28 });
    doc.fillColor('#6b7280').fontSize(8.5).font('Helvetica').text(b.label.toUpperCase(), x + 14, y + 38);
  });
  doc.y += 2 * (boxH + gap) + 10;

  doc.fontSize(9.5).fillColor('#374151').font('Helvetica').text(
    `${summary.works} completed work(s)  •  ${summary.payment_count} staff payment(s)`
  );
  doc.moveDown(0.8);

  // Breakdown table
  doc.fontSize(9).fillColor('#ffffff');
  doc.rect(48, doc.y, 510, 20).fill('#312e81');
  doc.fillColor('#ffffff').font('Helvetica-Bold');
  const cols = [
    { t: 'Period', x: 54, w: 64 },
    { t: 'Works', x: 122, w: 40, align: 'right' },
    { t: 'Income', x: 170, w: 78, align: 'right' },
    { t: 'Expense', x: 252, w: 78, align: 'right' },
    { t: 'Profit', x: 334, w: 78, align: 'right' },
    { t: 'Paid to staff', x: 416, w: 140, align: 'right' },
  ];
  for (const c of cols) doc.text(c.t, c.x, doc.y + 6, { width: c.w, align: c.align || 'left' });
  doc.moveDown(1.1);

  doc.font('Helvetica').fillColor('#111827');
  if (!rows.length) {
    doc.fontSize(9.5).text('No completed works or staff payments in this period.', 54, doc.y);
  } else {
    for (const r of rows) {
      const y = doc.y;
      doc.fontSize(9);
      const vals = [
        { t: r.key, x: 54, w: 64 },
        { t: `${r.works} (${r.payment_count} pay)`, x: 122, w: 40, align: 'right' },
        { t: money(r.income), x: 170, w: 78, align: 'right' },
        { t: money(r.expense), x: 252, w: 78, align: 'right' },
        { t: money(r.profit), x: 334, w: 78, align: 'right' },
        { t: money(r.payments), x: 416, w: 140, align: 'right' },
      ];
      for (const v of vals) doc.text(v.t, v.x, y, { width: v.w, align: v.align || 'left' });
      doc.moveDown(0.45);
    }
  }

  doc.moveDown(1.4);
  doc.fontSize(9).fillColor('#9ca3af').font('Helvetica').text(
    `Generated by ${COMPANY_NAME} • Financial report for ${from} to ${to}`,
    { align: 'center' }
  );

  doc.end();
}

/** Build the WhatsApp share message for a quotation. */
export function quotationWhatsAppMessage(q) {
  const items = typeof q.items === 'string' ? JSON.parse(q.items) : q.items || [];
  const lines = [
    `*${COMPANY_NAME}*`,
    `Quotation *${q.quotation_number}*`,
    '',
    `Client: ${q.client_name}`,
    q.event_name ? `Event: ${q.event_name}` : null,
    q.event_date ? `Event date: ${q.event_date}` : null,
    '',
    ...items.map((it, i) => `${i + 1}. ${it.description} x${it.qty ?? 1} = ${money((Number(it.qty) || 0) * (Number(it.unit_price) || 0))}`),
    '',
    `*Total: ${money(q.total)}*`,
    q.notes ? `Notes: ${q.notes}` : null,
    '',
    'Please confirm to book your event. Thank you!',
  ].filter(Boolean);
  return lines.join('\n');
}

export function waLink(phone, message) {
  const digits = String(phone || '').replace(/[^\d]/g, '');
  return `https://wa.me/${digits}?text=${encodeURIComponent(message)}`;
}